### ISSUE TITLE
Possibility to cancel/delete a download in progress

### ISSUE THREAD

**Issue by remi-chapelain** [remichat/fetchify#47]
Like if you made a mistake and tried 5 times to download the same playlist

**Comment by remichat** [comment]
Done.
But now I'm wondering why you tried 5 times to download the same playlist ;)

**Comment by remi-chapelain** [comment]
Because, it wasn't instant, so I thought it was not working, tried clicked one more time... etc ;)

**Comment by remichat** [comment]
Ah yes, I added a toast after you created this ticket 👍
